import "../globals.css";
export const metadata = {
  title: "Restaurent",
  description: "Generated by create next app",
};
export default function RestaurantLayout({ children }) {
  return <>{children}</>;
}
